web/router.ex
defmodule Blogger.Router do
  use Blogger.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Blogger.Plugs.SetUser 
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Blogger do
    pipe_through :browser # Use the default browser stack

    get "/", AuthController, :index


  end

  scope "/api", Blogger do
    pipe_through :api

    post "/posts", PostController, :create
    get "/posts", PostController, :all
    put "/posts/:id", PostController, :update
    delete "/posts/:id", PostController, :delete
  end

  scope "/posts", Blogger do
    pipe_through :browser

    get "/", PostController, :index
    get "/new", PostController, :new
  end

  scope "/auth", Blogger do
    pipe_through :browser # Use the default browser stack

    get "/signup", AuthController, :signup
    post "/saveuser", AuthController, :saveuser
    post "/login", AuthController, :login
    get "/signout", AuthController, :signout

  end

  scope "/activities", Blogger do
    pipe_through :browser

    get "/", ActivityController, :index
    get "/new", ActivityController, :new
    post "/create", ActivityController, :create
    get "/like/:id", ActivityController, :like
    get "/dislike/:id", ActivityController, :dislike
  end

  # Other scopes may use custom stacks.
  # scope "/api", Blogger do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Blogger.LayoutView do
  use Blogger.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Blogger!</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>

  <nav>
    <div class="nav-wrapper container">
      <a href="/" class="brand-logo">Blogger</a>
      <ul id="nav" class="right">

        
          <%= if @conn.assigns[:user] do %>
            <li>
              <a class='dropdown-trigger' href='#' data-target='dropdown1'>Hello, <%= @conn.assigns[:user].name %> </a>
            </li>
            <ul id='dropdown1' class='dropdown-content'>
              <li>
                <%= link "My Posts", to: post_path(@conn, :index) %>
              </li>
                <li> <%= link "Activities", to: activity_path(@conn, :index) %> </li>
               <li> <%= link "Sign Out", to: auth_path(@conn, :signout) %> </li>
            </ul>
        <% else %>
          <li>
            <%= link "Login", to: auth_path(@conn, :index) %>
          </li>
          <li>
            <%= link "Register", to: auth_path(@conn, :signup) %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

    <div class="container-fluid">


      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          var elems = document.querySelectorAll('.dropdown-trigger');
          var instances = M.Dropdown.init(elems, {
            coverTrigger: false
          });
        });
      </script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

  </body>
</html>